# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/checkout_form.ui'
#
# Created: Sun Aug 26 15:58:37 2018
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CheckoutForm(object):
    def setupUi(self, CheckoutForm):
        CheckoutForm.setObjectName("CheckoutForm")
        CheckoutForm.resize(393, 229)
        CheckoutForm.setSizeGripEnabled(True)
        CheckoutForm.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(CheckoutForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtGui.QGroupBox(CheckoutForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.total_lb = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.total_lb.setFont(font)
        self.total_lb.setFrameShape(QtGui.QFrame.NoFrame)
        self.total_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_lb.setObjectName("total_lb")
        self.gridLayout.addWidget(self.total_lb, 0, 1, 1, 2)
        self.amount_due_lb = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.amount_due_lb.setFont(font)
        self.amount_due_lb.setFrameShape(QtGui.QFrame.NoFrame)
        self.amount_due_lb.setFrameShadow(QtGui.QFrame.Plain)
        self.amount_due_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amount_due_lb.setObjectName("amount_due_lb")
        self.gridLayout.addWidget(self.amount_due_lb, 3, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.discount_le = QtGui.QLineEdit(self.groupBox)
        self.discount_le.setInputMask("")
        self.discount_le.setText("")
        self.discount_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.discount_le.setObjectName("discount_le")
        self.gridLayout.addWidget(self.discount_le, 1, 1, 1, 2)
        self.percent_rb = QtGui.QRadioButton(self.groupBox)
        self.percent_rb.setChecked(True)
        self.percent_rb.setObjectName("percent_rb")
        self.gridLayout.addWidget(self.percent_rb, 2, 1, 1, 1)
        self.absolute_rb = QtGui.QRadioButton(self.groupBox)
        self.absolute_rb.setObjectName("absolute_rb")
        self.gridLayout.addWidget(self.absolute_rb, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.cash_le = QtGui.QLineEdit(self.groupBox)
        self.cash_le.setText("")
        self.cash_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cash_le.setObjectName("cash_le")
        self.gridLayout.addWidget(self.cash_le, 4, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.change_lb = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.change_lb.setFont(font)
        self.change_lb.setFrameShape(QtGui.QFrame.NoFrame)
        self.change_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.change_lb.setObjectName("change_lb")
        self.gridLayout.addWidget(self.change_lb, 5, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(CheckoutForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.discount_le)
        self.label_3.setBuddy(self.cash_le)

        self.retranslateUi(CheckoutForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CheckoutForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CheckoutForm.reject)
        QtCore.QMetaObject.connectSlotsByName(CheckoutForm)
        CheckoutForm.setTabOrder(self.percent_rb, self.absolute_rb)
        CheckoutForm.setTabOrder(self.absolute_rb, self.discount_le)
        CheckoutForm.setTabOrder(self.discount_le, self.cash_le)
        CheckoutForm.setTabOrder(self.cash_le, self.buttonBox)

    def retranslateUi(self, CheckoutForm):
        CheckoutForm.setWindowTitle(QtGui.QApplication.translate("CheckoutForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CheckoutForm", "Checkout", None, QtGui.QApplication.UnicodeUTF8))
        self.total_lb.setText(QtGui.QApplication.translate("CheckoutForm", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.amount_due_lb.setText(QtGui.QApplication.translate("CheckoutForm", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CheckoutForm", "Total Amount :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CheckoutForm", "&Discount :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CheckoutForm", "Amount Due :", None, QtGui.QApplication.UnicodeUTF8))
        self.discount_le.setPlaceholderText(QtGui.QApplication.translate("CheckoutForm", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.percent_rb.setText(QtGui.QApplication.translate("CheckoutForm", "P&ercent", None, QtGui.QApplication.UnicodeUTF8))
        self.absolute_rb.setText(QtGui.QApplication.translate("CheckoutForm", "M&onetary", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CheckoutForm", "&Cash Tendered :", None, QtGui.QApplication.UnicodeUTF8))
        self.cash_le.setPlaceholderText(QtGui.QApplication.translate("CheckoutForm", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CheckoutForm", "Change Due :", None, QtGui.QApplication.UnicodeUTF8))
        self.change_lb.setText(QtGui.QApplication.translate("CheckoutForm", "0.00", None, QtGui.QApplication.UnicodeUTF8))

