# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_window.ui'
#
# Created: Sun Aug 26 20:33:51 2018
#      by: pyside-uic 0.2.13 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 507)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_caption_lb = QtGui.QLabel(self.centralwidget)
        self.table_caption_lb.setObjectName("table_caption_lb")
        self.horizontalLayout_2.addWidget(self.table_caption_lb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.search_product_le = QtGui.QLineEdit(self.centralwidget)
        self.search_product_le.setObjectName("search_product_le")
        self.horizontalLayout_2.addWidget(self.search_product_le)
        self.clear_product_search_pb = QtGui.QPushButton(self.centralwidget)
        self.clear_product_search_pb.setObjectName("clear_product_search_pb")
        self.horizontalLayout_2.addWidget(self.clear_product_search_pb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.products_tw = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.products_tw.sizePolicy().hasHeightForWidth())
        self.products_tw.setSizePolicy(sizePolicy)
        self.products_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.products_tw.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.products_tw.setAlternatingRowColors(True)
        self.products_tw.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.products_tw.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.products_tw.setObjectName("products_tw")
        self.products_tw.setColumnCount(0)
        self.products_tw.setRowCount(0)
        self.verticalLayout_4.addWidget(self.products_tw)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.home_pb = QtGui.QPushButton(self.centralwidget)
        self.home_pb.setObjectName("home_pb")
        self.horizontalLayout_3.addWidget(self.home_pb)
        self.pg_up_bp = QtGui.QPushButton(self.centralwidget)
        self.pg_up_bp.setObjectName("pg_up_bp")
        self.horizontalLayout_3.addWidget(self.pg_up_bp)
        self.pg_down_pb = QtGui.QPushButton(self.centralwidget)
        self.pg_down_pb.setObjectName("pg_down_pb")
        self.horizontalLayout_3.addWidget(self.pg_down_pb)
        self.end_pb = QtGui.QPushButton(self.centralwidget)
        self.end_pb.setObjectName("end_pb")
        self.horizontalLayout_3.addWidget(self.end_pb)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.detailview_ckb = QtGui.QCheckBox(self.centralwidget)
        self.detailview_ckb.setObjectName("detailview_ckb")
        self.horizontalLayout_3.addWidget(self.detailview_ckb)
        self.add_product_pb = QtGui.QPushButton(self.centralwidget)
        self.add_product_pb.setObjectName("add_product_pb")
        self.horizontalLayout_3.addWidget(self.add_product_pb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.categories_dkw = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categories_dkw.sizePolicy().hasHeightForWidth())
        self.categories_dkw.setSizePolicy(sizePolicy)
        self.categories_dkw.setFloating(False)
        self.categories_dkw.setObjectName("categories_dkw")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_category_le = QtGui.QLineEdit(self.dockWidgetContents)
        self.search_category_le.setObjectName("search_category_le")
        self.horizontalLayout_4.addWidget(self.search_category_le)
        self.clear_category_search_pb = QtGui.QPushButton(self.dockWidgetContents)
        self.clear_category_search_pb.setObjectName("clear_category_search_pb")
        self.horizontalLayout_4.addWidget(self.clear_category_search_pb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.categories_lw = QtGui.QListWidget(self.dockWidgetContents)
        self.categories_lw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.categories_lw.setAlternatingRowColors(True)
        self.categories_lw.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.categories_lw.setObjectName("categories_lw")
        self.verticalLayout_2.addWidget(self.categories_lw)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.add_category_pb = QtGui.QPushButton(self.dockWidgetContents)
        self.add_category_pb.setObjectName("add_category_pb")
        self.horizontalLayout.addWidget(self.add_category_pb)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.categories_dkw.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.categories_dkw)
        self.cartitems_dkw = QtGui.QDockWidget(MainWindow)
        self.cartitems_dkw.setFloating(False)
        self.cartitems_dkw.setObjectName("cartitems_dkw")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cart_tw = QtGui.QTableWidget(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cart_tw.sizePolicy().hasHeightForWidth())
        self.cart_tw.setSizePolicy(sizePolicy)
        self.cart_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.cart_tw.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.cart_tw.setAlternatingRowColors(True)
        self.cart_tw.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.cart_tw.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.cart_tw.setObjectName("cart_tw")
        self.cart_tw.setColumnCount(0)
        self.cart_tw.setRowCount(0)
        self.verticalLayout_8.addWidget(self.cart_tw)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.checkout_pb = QtGui.QPushButton(self.dockWidgetContents_2)
        self.checkout_pb.setObjectName("checkout_pb")
        self.horizontalLayout_6.addWidget(self.checkout_pb)
        self.clear_cart_pb = QtGui.QPushButton(self.dockWidgetContents_2)
        self.clear_cart_pb.setObjectName("clear_cart_pb")
        self.horizontalLayout_6.addWidget(self.clear_cart_pb)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.cartitems_dkw.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.cartitems_dkw)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 28))
        self.menubar.setObjectName("menubar")
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setGeometry(QtCore.QRect(324, 156, 133, 206))
        self.menu_file.setObjectName("menu_file")
        self.menuNew = QtGui.QMenu(self.menu_file)
        self.menuNew.setObjectName("menuNew")
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.action_add_product = QtGui.QAction(MainWindow)
        self.action_add_product.setObjectName("action_add_product")
        self.action_add_category = QtGui.QAction(MainWindow)
        self.action_add_category.setObjectName("action_add_category")
        self.action_add_user = QtGui.QAction(MainWindow)
        self.action_add_user.setObjectName("action_add_user")
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_exit.setObjectName("action_exit")
        self.action_preferences = QtGui.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.action_show_sales = QtGui.QAction(MainWindow)
        self.action_show_sales.setCheckable(False)
        self.action_show_sales.setObjectName("action_show_sales")
        self.action_about = QtGui.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_toggle_categories = QtGui.QAction(MainWindow)
        self.action_toggle_categories.setCheckable(True)
        self.action_toggle_categories.setChecked(True)
        self.action_toggle_categories.setObjectName("action_toggle_categories")
        self.action_toggle_cartitems = QtGui.QAction(MainWindow)
        self.action_toggle_cartitems.setCheckable(True)
        self.action_toggle_cartitems.setChecked(True)
        self.action_toggle_cartitems.setObjectName("action_toggle_cartitems")
        self.menu_view.addAction(self.action_toggle_categories)
        self.menu_view.addAction(self.action_toggle_cartitems)
        self.menu_view.addSeparator()
        self.menuNew.addAction(self.action_add_product)
        self.menuNew.addAction(self.action_add_category)
        self.menuNew.addAction(self.action_add_user)
        self.menu_file.addAction(self.menuNew.menuAction())
        self.menu_file.addAction(self.action_show_sales)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_preferences)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.search_category_le, self.clear_category_search_pb)
        MainWindow.setTabOrder(self.clear_category_search_pb, self.categories_lw)
        MainWindow.setTabOrder(self.categories_lw, self.add_category_pb)
        MainWindow.setTabOrder(self.add_category_pb, self.cart_tw)
        MainWindow.setTabOrder(self.cart_tw, self.checkout_pb)
        MainWindow.setTabOrder(self.checkout_pb, self.clear_cart_pb)
        MainWindow.setTabOrder(self.clear_cart_pb, self.search_product_le)
        MainWindow.setTabOrder(self.search_product_le, self.clear_product_search_pb)
        MainWindow.setTabOrder(self.clear_product_search_pb, self.home_pb)
        MainWindow.setTabOrder(self.home_pb, self.pg_up_bp)
        MainWindow.setTabOrder(self.pg_up_bp, self.pg_down_pb)
        MainWindow.setTabOrder(self.pg_down_pb, self.end_pb)
        MainWindow.setTabOrder(self.end_pb, self.detailview_ckb)
        MainWindow.setTabOrder(self.detailview_ckb, self.add_product_pb)
        MainWindow.setTabOrder(self.add_product_pb, self.products_tw)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.table_caption_lb.setText(QtGui.QApplication.translate("MainWindow", "Table caption", None, QtGui.QApplication.UnicodeUTF8))
        self.search_product_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search product...", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_product_search_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.home_pb.setText(QtGui.QApplication.translate("MainWindow", "<< Home", None, QtGui.QApplication.UnicodeUTF8))
        self.pg_up_bp.setText(QtGui.QApplication.translate("MainWindow", "< Pg Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pg_down_pb.setText(QtGui.QApplication.translate("MainWindow", "Pg Down >", None, QtGui.QApplication.UnicodeUTF8))
        self.end_pb.setText(QtGui.QApplication.translate("MainWindow", "End >>", None, QtGui.QApplication.UnicodeUTF8))
        self.detailview_ckb.setText(QtGui.QApplication.translate("MainWindow", "&Show detailed view", None, QtGui.QApplication.UnicodeUTF8))
        self.add_product_pb.setText(QtGui.QApplication.translate("MainWindow", "New &Product", None, QtGui.QApplication.UnicodeUTF8))
        self.categories_dkw.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.search_category_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search category...", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_category_search_pb.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.add_category_pb.setText(QtGui.QApplication.translate("MainWindow", "New &Category", None, QtGui.QApplication.UnicodeUTF8))
        self.cartitems_dkw.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Cart Items", None, QtGui.QApplication.UnicodeUTF8))
        self.checkout_pb.setText(QtGui.QApplication.translate("MainWindow", "Check&out", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_cart_pb.setText(QtGui.QApplication.translate("MainWindow", "C&lear", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_view.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_file.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setTitle(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_product.setText(QtGui.QApplication.translate("MainWindow", "Product", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_product.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a new product", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_product.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_category.setText(QtGui.QApplication.translate("MainWindow", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_category.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a new category", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_category.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_user.setText(QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_user.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a new user", None, QtGui.QApplication.UnicodeUTF8))
        self.action_add_user.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+U", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit Application", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_preferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.action_preferences.setStatusTip(QtGui.QApplication.translate("MainWindow", "Change preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.action_preferences.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+J", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_sales.setText(QtGui.QApplication.translate("MainWindow", "Sales", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_sales.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show/Hide sales window", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_sales.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_toggle_categories.setText(QtGui.QApplication.translate("MainWindow", "Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.action_toggle_categories.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show/Hide categories", None, QtGui.QApplication.UnicodeUTF8))
        self.action_toggle_categories.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.action_toggle_cartitems.setText(QtGui.QApplication.translate("MainWindow", "Cart Items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_toggle_cartitems.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show/Hide cart items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_toggle_cartitems.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))

