# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/product_details.ui',
# licensing of 'forms/product_details.ui' applies.
#
# Created: Mon Oct 29 23:51:51 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ProductDetails(object):
    def setupUi(self, ProductDetails):
        ProductDetails.setObjectName("ProductDetails")
        ProductDetails.resize(426, 288)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductDetails)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ProductDetails)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name_lb = QtWidgets.QLabel(self.groupBox)
        self.name_lb.setText("")
        self.name_lb.setObjectName("name_lb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_lb)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sku_lb = QtWidgets.QLabel(self.groupBox)
        self.sku_lb.setText("")
        self.sku_lb.setObjectName("sku_lb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sku_lb)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.unit_cost_lb = QtWidgets.QLabel(self.groupBox)
        self.unit_cost_lb.setText("")
        self.unit_cost_lb.setObjectName("unit_cost_lb")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.unit_cost_lb)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.unit_price_lb = QtWidgets.QLabel(self.groupBox)
        self.unit_price_lb.setText("")
        self.unit_price_lb.setObjectName("unit_price_lb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.unit_price_lb)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.description_lb = QtWidgets.QLabel(self.groupBox)
        self.description_lb.setText("")
        self.description_lb.setObjectName("description_lb")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.description_lb)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.created_at_lb = QtWidgets.QLabel(self.groupBox)
        self.created_at_lb.setText("")
        self.created_at_lb.setObjectName("created_at_lb")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.created_at_lb)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.modified_at_lb = QtWidgets.QLabel(self.groupBox)
        self.modified_at_lb.setText("")
        self.modified_at_lb.setObjectName("modified_at_lb")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.modified_at_lb)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.units_lb = QtWidgets.QLabel(self.groupBox)
        self.units_lb.setText("")
        self.units_lb.setObjectName("units_lb")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.units_lb)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.category_lb = QtWidgets.QLabel(self.groupBox)
        self.category_lb.setText("")
        self.category_lb.setObjectName("category_lb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.category_lb)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProductDetails)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProductDetails)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ProductDetails.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ProductDetails.reject)
        QtCore.QMetaObject.connectSlotsByName(ProductDetails)

    def retranslateUi(self, ProductDetails):
        ProductDetails.setWindowTitle(QtWidgets.QApplication.translate("ProductDetails", "Dialog", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ProductDetails", "Product Details", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ProductDetails", "Name :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("ProductDetails", "SKU :", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("ProductDetails", "Unit Cost :", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("ProductDetails", "Unit Price :", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("ProductDetails", "Description :", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("ProductDetails", "Created :", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("ProductDetails", "Last modified :", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("ProductDetails", "Units :", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("ProductDetails", "Category :", None, -1))

