# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/user_form.ui',
# licensing of 'forms/user_form.ui' applies.
#
# Created: Mon Oct 29 23:51:51 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_UserForm(object):
    def setupUi(self, UserForm):
        UserForm.setObjectName("UserForm")
        UserForm.resize(629, 361)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(UserForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.avatar_lb = QtWidgets.QLabel(self.groupBox)
        self.avatar_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar_lb.setObjectName("avatar_lb")
        self.verticalLayout_2.addWidget(self.avatar_lb)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.username_le = QtWidgets.QLineEdit(self.groupBox)
        self.username_le.setObjectName("username_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_le)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password_le = QtWidgets.QLineEdit(self.groupBox)
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setObjectName("password_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_le)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.password_2_le = QtWidgets.QLineEdit(self.groupBox)
        self.password_2_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2_le.setObjectName("password_2_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_2_le)
        self.error_lb = QtWidgets.QLabel(self.groupBox)
        self.error_lb.setStyleSheet("color: #B22222;")
        self.error_lb.setObjectName("error_lb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.error_lb)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.admin_ckb = QtWidgets.QCheckBox(self.groupBox)
        self.admin_ckb.setObjectName("admin_ckb")
        self.verticalLayout_2.addWidget(self.admin_ckb)
        spacerItem2 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(UserForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.username_le)
        self.label_2.setBuddy(self.password_le)
        self.label_3.setBuddy(self.password_2_le)

        self.retranslateUi(UserForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), UserForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), UserForm.reject)
        QtCore.QMetaObject.connectSlotsByName(UserForm)
        UserForm.setTabOrder(self.username_le, self.password_le)
        UserForm.setTabOrder(self.password_le, self.password_2_le)
        UserForm.setTabOrder(self.password_2_le, self.admin_ckb)
        UserForm.setTabOrder(self.admin_ckb, self.buttonBox)

    def retranslateUi(self, UserForm):
        UserForm.setWindowTitle(QtWidgets.QApplication.translate("UserForm", "Dialog", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("UserForm", "Add new user", None, -1))
        self.avatar_lb.setText(QtWidgets.QApplication.translate("UserForm", "Avatar", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("UserForm", "&Username :", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("UserForm", "&Password :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("UserForm", "&Retype Password :", None, -1))
        self.error_lb.setText(QtWidgets.QApplication.translate("UserForm", "Password do not match", None, -1))
        self.admin_ckb.setText(QtWidgets.QApplication.translate("UserForm", "A&dministrative privilege", None, -1))

