# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/checkout_form.ui',
# licensing of 'forms/checkout_form.ui' applies.
#
# Created: Tue Jan 29 22:11:15 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CheckoutForm(object):
    def setupUi(self, CheckoutForm):
        CheckoutForm.setObjectName("CheckoutForm")
        CheckoutForm.resize(393, 286)
        CheckoutForm.setSizeGripEnabled(True)
        CheckoutForm.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CheckoutForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(CheckoutForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.discount_le = QtWidgets.QLineEdit(self.groupBox)
        self.discount_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.discount_le.setObjectName("discount_le")
        self.gridLayout.addWidget(self.discount_le, 1, 1, 1, 2)
        self.absolute_rb = QtWidgets.QRadioButton(self.groupBox)
        self.absolute_rb.setChecked(True)
        self.absolute_rb.setObjectName("absolute_rb")
        self.gridLayout.addWidget(self.absolute_rb, 2, 1, 1, 1)
        self.percent_rb = QtWidgets.QRadioButton(self.groupBox)
        self.percent_rb.setChecked(False)
        self.percent_rb.setObjectName("percent_rb")
        self.gridLayout.addWidget(self.percent_rb, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.cash_le = QtWidgets.QLineEdit(self.groupBox)
        self.cash_le.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cash_le.setObjectName("cash_le")
        self.gridLayout.addWidget(self.cash_le, 4, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.total_lb = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.total_lb.setFont(font)
        self.total_lb.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.total_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_lb.setObjectName("total_lb")
        self.gridLayout.addWidget(self.total_lb, 0, 1, 1, 2)
        self.amount_due_lb = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.amount_due_lb.setFont(font)
        self.amount_due_lb.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.amount_due_lb.setFrameShadow(QtWidgets.QFrame.Plain)
        self.amount_due_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amount_due_lb.setObjectName("amount_due_lb")
        self.gridLayout.addWidget(self.amount_due_lb, 3, 1, 1, 2)
        self.change_lb = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.change_lb.setFont(font)
        self.change_lb.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.change_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.change_lb.setObjectName("change_lb")
        self.gridLayout.addWidget(self.change_lb, 5, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(CheckoutForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.discount_le)
        self.label_3.setBuddy(self.cash_le)

        self.retranslateUi(CheckoutForm)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CheckoutForm.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CheckoutForm.reject)
        QtCore.QMetaObject.connectSlotsByName(CheckoutForm)
        CheckoutForm.setTabOrder(self.discount_le, self.cash_le)
        CheckoutForm.setTabOrder(self.cash_le, self.buttonBox)

    def retranslateUi(self, CheckoutForm):
        CheckoutForm.setWindowTitle(QtWidgets.QApplication.translate("CheckoutForm", "Dialog", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("CheckoutForm", "Checkout", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("CheckoutForm", "Total Amount :", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("CheckoutForm", "&Discount :", None, -1))
        self.discount_le.setPlaceholderText(QtWidgets.QApplication.translate("CheckoutForm", "0.00", None, -1))
        self.absolute_rb.setText(QtWidgets.QApplication.translate("CheckoutForm", "A&bsolute", None, -1))
        self.percent_rb.setText(QtWidgets.QApplication.translate("CheckoutForm", "P&ercent", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("CheckoutForm", "Amount Due :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("CheckoutForm", "C&ash Tendered :", None, -1))
        self.cash_le.setPlaceholderText(QtWidgets.QApplication.translate("CheckoutForm", "0.00", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("CheckoutForm", "Change Due :", None, -1))
        self.total_lb.setText(QtWidgets.QApplication.translate("CheckoutForm", "0.00", None, -1))
        self.amount_due_lb.setText(QtWidgets.QApplication.translate("CheckoutForm", "0.00", None, -1))
        self.change_lb.setText(QtWidgets.QApplication.translate("CheckoutForm", "0.00", None, -1))

