# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_window.ui',
# licensing of 'forms/main_window.ui' applies.
#
# Created: Fri Mar  8 11:13:46 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 507)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.table_caption_lb = QtWidgets.QLabel(self.centralwidget)
        self.table_caption_lb.setObjectName("table_caption_lb")
        self.horizontalLayout_2.addWidget(self.table_caption_lb)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.search_product_le = QtWidgets.QLineEdit(self.centralwidget)
        self.search_product_le.setStyleSheet("")
        self.search_product_le.setObjectName("search_product_le")
        self.horizontalLayout_2.addWidget(self.search_product_le)
        self.clear_product_search_pb = QtWidgets.QToolButton(self.centralwidget)
        self.clear_product_search_pb.setStyleSheet("")
        self.clear_product_search_pb.setText("")
        self.clear_product_search_pb.setObjectName("clear_product_search_pb")
        self.horizontalLayout_2.addWidget(self.clear_product_search_pb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.products_tw = QtWidgets.QTableWidget(self.centralwidget)
        self.products_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.products_tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.products_tw.setAlternatingRowColors(True)
        self.products_tw.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.products_tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.products_tw.setShowGrid(False)
        self.products_tw.setObjectName("products_tw")
        self.products_tw.setColumnCount(0)
        self.products_tw.setRowCount(0)
        self.products_tw.horizontalHeader().setHighlightSections(True)
        self.products_tw.verticalHeader().setVisible(False)
        self.products_tw.verticalHeader().setHighlightSections(True)
        self.verticalLayout_4.addWidget(self.products_tw)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.home_pb = QtWidgets.QToolButton(self.centralwidget)
        self.home_pb.setText("")
        self.home_pb.setIconSize(QtCore.QSize(24, 24))
        self.home_pb.setObjectName("home_pb")
        self.horizontalLayout_3.addWidget(self.home_pb)
        self.pg_up_pb = QtWidgets.QToolButton(self.centralwidget)
        self.pg_up_pb.setText("")
        self.pg_up_pb.setIconSize(QtCore.QSize(24, 24))
        self.pg_up_pb.setObjectName("pg_up_pb")
        self.horizontalLayout_3.addWidget(self.pg_up_pb)
        self.pg_down_pb = QtWidgets.QToolButton(self.centralwidget)
        self.pg_down_pb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pg_down_pb.setText("")
        self.pg_down_pb.setIconSize(QtCore.QSize(24, 24))
        self.pg_down_pb.setObjectName("pg_down_pb")
        self.horizontalLayout_3.addWidget(self.pg_down_pb)
        self.end_pb = QtWidgets.QToolButton(self.centralwidget)
        self.end_pb.setStyleSheet("")
        self.end_pb.setText("")
        self.end_pb.setIconSize(QtCore.QSize(24, 24))
        self.end_pb.setObjectName("end_pb")
        self.horizontalLayout_3.addWidget(self.end_pb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.detailview_ckb = QtWidgets.QCheckBox(self.centralwidget)
        self.detailview_ckb.setObjectName("detailview_ckb")
        self.horizontalLayout_3.addWidget(self.detailview_ckb)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.categories_dkw = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categories_dkw.sizePolicy().hasHeightForWidth())
        self.categories_dkw.setSizePolicy(sizePolicy)
        self.categories_dkw.setFloating(False)
        self.categories_dkw.setObjectName("categories_dkw")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_category_le = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.search_category_le.setObjectName("search_category_le")
        self.horizontalLayout_4.addWidget(self.search_category_le)
        self.clear_category_search_pb = QtWidgets.QToolButton(self.dockWidgetContents)
        self.clear_category_search_pb.setText("")
        self.clear_category_search_pb.setObjectName("clear_category_search_pb")
        self.horizontalLayout_4.addWidget(self.clear_category_search_pb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.categories_lw = QtWidgets.QListWidget(self.dockWidgetContents)
        self.categories_lw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.categories_lw.setAlternatingRowColors(True)
        self.categories_lw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.categories_lw.setObjectName("categories_lw")
        self.verticalLayout_2.addWidget(self.categories_lw)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.categories_dkw.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.categories_dkw)
        self.cartitems_dkw = QtWidgets.QDockWidget(MainWindow)
        self.cartitems_dkw.setFloating(False)
        self.cartitems_dkw.setObjectName("cartitems_dkw")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cartitems_tw = QtWidgets.QTableWidget(self.dockWidgetContents_2)
        self.cartitems_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.cartitems_tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cartitems_tw.setAlternatingRowColors(True)
        self.cartitems_tw.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.cartitems_tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.cartitems_tw.setShowGrid(False)
        self.cartitems_tw.setObjectName("cartitems_tw")
        self.cartitems_tw.setColumnCount(0)
        self.cartitems_tw.setRowCount(0)
        self.cartitems_tw.horizontalHeader().setHighlightSections(True)
        self.cartitems_tw.verticalHeader().setVisible(False)
        self.cartitems_tw.verticalHeader().setHighlightSections(True)
        self.verticalLayout_8.addWidget(self.cartitems_tw)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.cartitems_dkw.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.cartitems_dkw)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 28))
        self.menubar.setObjectName("menubar")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setGeometry(QtCore.QRect(298, 156, 144, 277))
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.action_add_product = QtWidgets.QAction(MainWindow)
        self.action_add_product.setObjectName("action_add_product")
        self.action_add_category = QtWidgets.QAction(MainWindow)
        self.action_add_category.setObjectName("action_add_category")
        self.action_add_user = QtWidgets.QAction(MainWindow)
        self.action_add_user.setObjectName("action_add_user")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action_exit.setObjectName("action_exit")
        self.action_preferences = QtWidgets.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.action_show_sales = QtWidgets.QAction(MainWindow)
        self.action_show_sales.setCheckable(False)
        self.action_show_sales.setObjectName("action_show_sales")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_checkout = QtWidgets.QAction(MainWindow)
        self.action_checkout.setEnabled(False)
        self.action_checkout.setObjectName("action_checkout")
        self.action_clear_cart = QtWidgets.QAction(MainWindow)
        self.action_clear_cart.setEnabled(False)
        self.action_clear_cart.setObjectName("action_clear_cart")
        self.action_about_qt = QtWidgets.QAction(MainWindow)
        self.action_about_qt.setObjectName("action_about_qt")
        self.action_toggle_categories = QtWidgets.QAction(MainWindow)
        self.action_toggle_categories.setCheckable(True)
        self.action_toggle_categories.setChecked(True)
        self.action_toggle_categories.setObjectName("action_toggle_categories")
        self.action_toggle_cartitems = QtWidgets.QAction(MainWindow)
        self.action_toggle_cartitems.setCheckable(True)
        self.action_toggle_cartitems.setChecked(True)
        self.action_toggle_cartitems.setObjectName("action_toggle_cartitems")
        self.menu_view.addAction(self.action_toggle_categories)
        self.menu_view.addAction(self.action_toggle_cartitems)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_show_sales)
        self.menu_file.addAction(self.action_checkout)
        self.menu_file.addAction(self.action_clear_cart)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_add_product)
        self.menu_file.addAction(self.action_add_category)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_preferences)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_help.addAction(self.action_about)
        self.menu_help.addAction(self.action_about_qt)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_toggle_categories, QtCore.SIGNAL("triggered(bool)"), self.categories_dkw.setVisible)
        QtCore.QObject.connect(self.action_toggle_cartitems, QtCore.SIGNAL("triggered(bool)"), self.cartitems_dkw.setVisible)
        QtCore.QObject.connect(self.clear_category_search_pb, QtCore.SIGNAL("clicked()"), self.search_category_le.clear)
        QtCore.QObject.connect(self.clear_category_search_pb, QtCore.SIGNAL("clicked()"), self.search_category_le.setFocus)
        QtCore.QObject.connect(self.clear_product_search_pb, QtCore.SIGNAL("clicked()"), self.search_product_le.clear)
        QtCore.QObject.connect(self.clear_product_search_pb, QtCore.SIGNAL("clicked()"), self.search_product_le.setFocus)
        QtCore.QObject.connect(self.home_pb, QtCore.SIGNAL("clicked()"), self.products_tw.scrollToTop)
        QtCore.QObject.connect(self.end_pb, QtCore.SIGNAL("clicked()"), self.products_tw.scrollToBottom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.search_category_le, self.clear_category_search_pb)
        MainWindow.setTabOrder(self.clear_category_search_pb, self.categories_lw)
        MainWindow.setTabOrder(self.categories_lw, self.cartitems_tw)
        MainWindow.setTabOrder(self.cartitems_tw, self.search_product_le)
        MainWindow.setTabOrder(self.search_product_le, self.clear_product_search_pb)
        MainWindow.setTabOrder(self.clear_product_search_pb, self.home_pb)
        MainWindow.setTabOrder(self.home_pb, self.pg_up_pb)
        MainWindow.setTabOrder(self.pg_up_pb, self.pg_down_pb)
        MainWindow.setTabOrder(self.pg_down_pb, self.detailview_ckb)
        MainWindow.setTabOrder(self.detailview_ckb, self.products_tw)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.table_caption_lb.setText(QtWidgets.QApplication.translate("MainWindow", "Table caption", None, -1))
        self.search_product_le.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search product...", None, -1))
        self.detailview_ckb.setText(QtWidgets.QApplication.translate("MainWindow", "Show &details", None, -1))
        self.categories_dkw.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Categories", None, -1))
        self.search_category_le.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search category...", None, -1))
        self.cartitems_dkw.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Cart Items", None, -1))
        self.menu_view.setTitle(QtWidgets.QApplication.translate("MainWindow", "&View", None, -1))
        self.menu_file.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menu_help.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Help", None, -1))
        self.action_add_product.setText(QtWidgets.QApplication.translate("MainWindow", "Add Product", None, -1))
        self.action_add_product.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Add a new product", None, -1))
        self.action_add_product.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.action_add_category.setText(QtWidgets.QApplication.translate("MainWindow", "Add Category", None, -1))
        self.action_add_category.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Add a new category", None, -1))
        self.action_add_category.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Add a new product category", None, -1))
        self.action_add_category.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Alt+N", None, -1))
        self.action_add_user.setText(QtWidgets.QApplication.translate("MainWindow", "Create User", None, -1))
        self.action_add_user.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Create a new user account", None, -1))
        self.action_add_user.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+U", None, -1))
        self.action_exit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.action_exit.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Exit application", None, -1))
        self.action_exit.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.action_exit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.action_preferences.setText(QtWidgets.QApplication.translate("MainWindow", "Preferences", None, -1))
        self.action_preferences.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Preferences", None, -1))
        self.action_preferences.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+J", None, -1))
        self.action_show_sales.setText(QtWidgets.QApplication.translate("MainWindow", "Show sales", None, -1))
        self.action_show_sales.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Show sales window", None, -1))
        self.action_show_sales.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+L", None, -1))
        self.action_about.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.action_checkout.setText(QtWidgets.QApplication.translate("MainWindow", "Checkout", None, -1))
        self.action_checkout.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Go to checkout", None, -1))
        self.action_checkout.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+Return", None, -1))
        self.action_clear_cart.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Cart Items", None, -1))
        self.action_clear_cart.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Remove all items from the cart", None, -1))
        self.action_clear_cart.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+-", None, -1))
        self.action_about_qt.setText(QtWidgets.QApplication.translate("MainWindow", "About Qt", None, -1))
        self.action_about_qt.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "About Qt", None, -1))
        self.action_toggle_categories.setText(QtWidgets.QApplication.translate("MainWindow", "Categories", None, -1))
        self.action_toggle_categories.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Show/Hide Categories", None, -1))
        self.action_toggle_categories.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+G", None, -1))
        self.action_toggle_cartitems.setText(QtWidgets.QApplication.translate("MainWindow", "CartItems", None, -1))
        self.action_toggle_cartitems.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Show/Hide CartItems", None, -1))
        self.action_toggle_cartitems.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I", None, -1))

